### ISSUE TITLE
Office League - Minor bugs - Batch 2

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/app-office-league#212]
[x] Rating sometimes stored as double
[x] Remove hover effect on title
[x] Switch player on miggame
[x] Expected score on pause
[x] Fail to reimport this morning? (if the player exists it failed, probably did not delete all data before import)
[x] Add pattern of name of create/edit player name (For @ for example)
[x] Spinner color
[x] See more teams: Remove player name/picture 
[x] Sometimes the edit profile form shows all empty fields

**Comment by GlennRicaud** [comment]
Exception:

java.lang.IllegalStateException: Invalid BundleContext.
	at org.apache.felix.framework.BundleContextImpl.checkValidity(BundleContextImpl.java:511) ~[org.apache.felix.framework-5.2.0.jar:na]
	at org.apache.felix.framework.BundleContextImpl.getServiceReference(BundleContextImpl.java:360) ~[org.apache.felix.framework-5.2.0.jar:na]
	at org.apache.felix.framework.BundleContextImpl.getServiceReference(BundleContextImpl.java:381) ~[org.apache.felix.framework-5.2.0.jar:na]
	at com.enonic.xp.script.impl.service.ServiceRefImpl.findService(ServiceRefImpl.java:33) ~[script-impl-6.10.0-RC2.jar:6.10.0-RC2]
	at com.enonic.xp.script.impl.service.ServiceRefImpl.get(ServiceRefImpl.java:22) ~[script-impl-6.10.0-RC2.jar:6.10.0-RC2]
	at com.enonic.xp.lib.websocket.AbstractWebSocketBean.initialize(AbstractWebSocketBean.java:15) ~[na:na]
	at com.enonic.xp.script.impl.bean.ScriptBeanFactoryImpl.injectBean(ScriptBeanFactoryImpl.java:34) ~[script-impl-6.10.0-RC2.jar:6.10.0-RC2]
	at com.enonic.xp.script.impl.bean.ScriptBeanFactoryImpl.newBean(ScriptBeanFactoryImpl.java:26) ~[script-impl-6.10.0-RC2.jar:6.10.0-RC2]
	at com.enonic.xp.script.impl.function.ScriptFunctions.newBean(ScriptFunctions.java:68) ~[script-impl-6.10.0-RC2.jar:6.10.0-RC2]
	at jdk.nashorn.internal.scripts.Script$Recompilation$4882$1415AA$websocket.L:1#sendToGroup(com.enonic.app.officeleague:/site/lib/xp/websocket.js:58) ~[na:na]
	at jdk.nashorn.internal.scripts.Script$Recompilation$4881$1362A$live_game.L:1#callback(com.enonic.app.officeleague:/services/live-game/live-game.js:57) ~[na:na]
	at jdk.nashorn.internal.scripts.Script$Recompilation$4400$745A$event.L:1#listener#listener(com.enonic.app.officeleague:/lib/xp/event.js:26) ~[na:na]
	at jdk.nashorn.javaadapters.java.util.function.Consumer.accept(Unknown Source) ~[na:na]
	at com.enonic.xp.script.event.ScriptEventListenerImpl.onEvent(ScriptEventListenerImpl.java:47) ~[script-api-6.10.0-RC2.jar:6.10.0-RC2]
	at com.enonic.xp.script.impl.event.ScriptEventManagerImpl.onEvent(ScriptEventManagerImpl.java:52) [script-impl-6.10.0-RC2.jar:6.10.0-RC2]
	at com.enonic.xp.core.impl.event.EventMulticaster.publish(EventMulticaster.java:51) [core-event-6.10.0-RC2.jar:6.10.0-RC2]
	at com.enonic.xp.core.impl.event.EventMulticaster.publish(EventMulticaster.java:43) [core-event-6.10.0-RC2.jar:6.10.0-RC2]
	at com.enonic.xp.core.impl.event.EventPublisherImpl.lambda$dispatchEvent$0(EventPublisherImpl.java:66) [core-event-6.10.0-RC2.jar:6.10.0-RC2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]
