### ISSUE TITLE
Office League - Video - com.enonic.xp.portal.impl.rendering.RenderException

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/app-office-league#237]
LOG TAIL
Start   ▲   ▼   End   Tail   
 Caused by: com.enonic.xp.portal.impl.rendering.RenderException: Failed to post process document
	at com.enonic.xp.portal.impl.parser.HtmlBlockParser.parse(HtmlBlockParser.java:41) ~[na:na]
	at com.enonic.xp.portal.impl.postprocess.PostProcessEvaluator.evaluateInstructions(PostProcessEvaluator.java:55) ~[na:na]
	at com.enonic.xp.portal.impl.postprocess.PostProcessorImpl.processResponseInstructions(PostProcessorImpl.java:69) ~[na:na]
	at com.enonic.xp.portal.impl.rendering.PageRenderer.render(PageRenderer.java:73) ~[na:na]
	at com.enonic.xp.portal.impl.rendering.PageRenderer.render(PageRenderer.java:31) ~[na:na]
	at com.enonic.xp.portal.impl.handler.mapping.MappingHandlerWorker.renderPage(MappingHandlerWorker.java:64) ~[na:na]
	at com.enonic.xp.portal.impl.handler.mapping.MappingHandlerWorker.execute(MappingHandlerWorker.java:50) ~[na:na]
	at com.enonic.xp.trace.Tracer.traceEx(Tracer.java:69) ~[core-api-6.10.0-RC2.jar:6.10.0-RC2]
	at com.enonic.xp.portal.impl.handler.mapping.MappingHandler.doHandle(MappingHandler.java:64) ~[na:na]
	at com.enonic.xp.portal.impl.handler.mapping.MappingHandler.doHandle(MappingHandler.java:23) ~[na:na]
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:71) [web-api-6.10.0-RC2.jar:6.10.0-RC2]
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30) [web-impl-6.10.0-RC2.jar:6.10.0-RC2]
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75) [web-api-6.10.0-RC2.jar:6.10.0-RC2]
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30) [web-impl-6.10.0-RC2.jar:6.10.0-RC2]
	at com.enonic.xp.portal.handler.BasePortalHandler.doHandle(BasePortalHandler.java:48) [portal-api-6.10.0-RC2.jar:6.10.0-RC2]
	... 93 common frames omitted

**Comment by aro** [comment]
Problem was in the attachmentUrl in video component. We just need to specify the attachment label, content id is implicit for the current page.

@torlokken  It is also possible to upload videos now from admin, the redirect issue in edit mode is fixed.
I am not sure how multiple video types should be handled (mp3, ogg...).
